const THEORIES = [
    { title: "Moon Landing Hoax", category: "Government", description: "In July 1969, NASA claimed to land humans on the Moon — but skeptics say the photos look too perfect. Shadows fall at odd angles, the flag waves in a vacuum, and Stanley Kubrick's 2001 looks suspiciously similar. The official story says it was real; the theorists say Kubrick directed the whole thing in a studio. Either way, the US had every reason to win the Space Race against the Soviets at any cost." },
    { title: "Flat Earth", category: "Science & Tech", description: "Believers say the Earth is a flat disc, with the Arctic at the center and a 150-foot ice wall (what we call Antarctica) forming the rim. NASA, airlines, and every government are allegedly colluding to hide this. Ships don't fall off the edge because the wall stops them. The sun and moon are small spotlights circling overhead — not distant celestial bodies." },
    { title: "The Illuminati", category: "Elite & Power", description: "A secret society of elites — bankers, politicians, celebrities — allegedly pulling every string on Earth. Founded in Bavaria in 1776, they supposedly never disbanded and now control the media, governments, and global finance. The all-seeing eye on the US dollar, Jay-Z's triangle hand gesture, and certain music videos are cited as open signals. Their goal: a single world government with them in charge." },
    { title: "Area 51", category: "Alien & Space", description: "A classified US Air Force base in the Nevada desert that the government denied even existed until 2013. Theorists say it houses crashed UFOs, alien bodies from Roswell, and reverse-engineered alien technology. The extreme secrecy, restricted airspace, and camouflage-uniformed gu <truncated 45215 bytes> age. The 'before and after 30' facial bone structure changes are attributed to the clone aging differently." },
    { title: "Nuclear Weapons Are a Bluff", category: "Government", description: "The theory: nuclear weapons don't actually work as described, and the entire deterrence regime is a mutually agreed fiction maintained by the five permanent UN Security Council members. The evidence cited: no wartime use since 1945, implausible yields described for bombs the size of a suitcase, and the fact that the only independent nuclear testing verification comes from the governments claiming to have the weapons." },
    { title: "The Sumerians Had Full Astronomical Knowledge", category: "Hidden History", description: "The Sumerian civilization of 3500 BCE had a fully formed pantheon, writing system, calendar, and astronomical record — appearing with no developmental period, unlike every other civilization. Their texts describe all eight planets of the solar system, including Uranus and Neptune — not discovered by modern astronomy until 1781 and 1846. Theorists say this knowledge was either inherited from an earlier advanced civilization or given by extraterrestrials they called the Anunnaki." },
    { title: "The Bilderberg Group Controls Policy", category: "Elite & Power", description: "Since 1954, around 130–140 of the world's most powerful people — heads of state, central bankers, military chiefs, tech CEOs — have met annually at the Bilderberg Group conference with no press, no minutes published, and no joint statement. What is decided is purely private. The group doesn't deny meeting — they release a rough topic list. Critics call it the world's most powerful unaccountable decision-making body." },
    { title: "The Taos Hum", category: "Science & Tech", description: "Since the 1990s, a small percentage of residents in Taos, New Mexi <truncated 10301 bytes>  NOTE: The output was truncated because it was too long. Use a more targeted query or a smaller range to get the information you need." }
];
